dist: xenial
services:
  - xvfb

language: node_js
node_js: 'lts/*'

cache:
  npm: false

addons:
  firefox: latest

script:
  - |
    npm run lint
    npm run test
    if [[ $TRAVIS_TAG == *"beta"* ]]; then
      npm run beta
    else
      unset WEB_EXT_API_KEY
      unset WEB_EXT_API_SECRET
      npm run build
    fi
    npm run test:functional
    npm run webext:lint
    npm run check:dependencies

after_success: npm run coverage

deploy:
  provider: releases
  prerelease: true
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: web-ext-artifacts/*
  skip_cleanup: true
  draft: true
  name: $TRAVIS_TAG
  on:
    tags: true
    condition: $TRAVIS_TAG =~ beta

after_deploy:
  - |
    if [[ $TRAVIS_TAG == *"beta"* ]]; then
      git clone --depth 1 --branch beta-updates https://github.com/stoically/temporary-containers.git
      cd temporary-containers
      export BETA_VERSION=$(echo $TRAVIS_TAG | sed "s/^v//")
      sed -i -e "s/[0-9]\+\.[0-9]\+\(beta[0-9]\+\)\?/$BETA_VERSION/g" updates.json
      sed -i -e "s/-fx\\.xpi/-an\\+fx\\.xpi/" updates.json
      git commit -am "$TRAVIS_TAG"
      git push https://$GITHUB_TOKEN:x-oauth-basic@github.com/stoically/temporary-containers.git/ beta-updates
    fi
